app:
  name: open_mall
  port: 8080
  mode: release


mysql:
  dsn: root:qwer1234@tcp(127.0.0.1:3306)/mall?charset=utf8mb4&parseTime=true&loc=Local
  maxidleconns: 10
  maxopenconns: 100


redis:
  host: 127.0.0.1:6379
  db: 0
